# region               = "ap-southeast-2"
# vpc_cidr_block       = "10.71.0.0/16"
# public_subnet        = ["10.71.1.0/24", "10.71.2.0/24"]
# private_subnet       = ["10.71.3.0/24", "10.71.4.0/24"]
# rds_subnet           = ["10.71.5.0/24", "10.71.6.0/24"]
# availability_zone    = ["ap-southeast-2a", "ap-southeast-2b"]
# project              = "TerraformIMS"
# tags_name            = {
#     myvpc                     = "r1-vpc-poc"
#     my_private_subnet         = "r1-sn-poc-pvt",
#     my_public_subnet          = "r1-sn-poc-pub",
#     my_rds_subnet        = "r1-sn-poc-rds"
#     my_internet_gateway       = "r1-igw-poc",
#     my_public_route_table     = "r1-rt-poc-pub",
#     my_private_route_table    = "r1-rt-poc-pvt",
#     my_rds_route_table        = "r1-rt-poc-rds",
#     my_nat_gateway            = "r1-nat-poc",
#     my_environment            = "Prod",
#     my_security_group_public  = "r1-sg-poc-pub",
#     my_security_group_private  = "r1-sg-poc-pvt",
#   }
